[project]
name = "cpgeo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "torch>=2.2.0",
    "torchvision>=0.17.0",
    "pypardiso>=0.4.7",
    "scipy>=1.16.3",
    "pyvista>=0.43.0",
]
